id: P004401
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:21.877327
source_metadata:
  id: bdr:W27520
  title: འདས་ལོག་ལྷ་མོ་ལྷམ་གཅུང་གི་རྣམ་ཐར་དམྱལ་བ་འགྲིམ་པའི་ལོ་རྒྱུས
  author: ''
  volumes:
    83bcf6336c724508bd0873030de25ac8:
      image_group_id: I4461
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
